### PR TITLE
Added support for Zclassic ( ZCL )

### PR DESCRIPTION
**Pull request by interbiznw**
This adds support for Zclassic ( ZCL )
https:/www.zclassic.org
https://github.com/z-classic/zclassic

### CODE REVIEW

**Comment by Mrwh0** [comment]
such great job.

**Comment by ch4ot1c** [comment]
http://zcl-explorer.com/ doesn't connect properly (granted, /insight/tx/* does work). May I suggest http://zclassicexplorer.com/tx/* instead? @interbiznw .

Other than that, Looks good to me!

**Comment by interbiznw** [comment]
> http://zcl-explorer.com/ doesn't connect properly (granted, /insight/tx/* does work). May I suggest 

the part in the code that says zcl-explorer.com is just the name, the actual link below that includes the transaction part of the url and variable, and if passed a transaction id like this, it works: http://zcl-explorer.com/insight/tx/2d89c614a9e570d2a6353376ae0a76447ea62bbbca114bf7b5df48c6e5524a21 

That is what is displayed when clicked on in ledger chrome app

**Comment by rankify** [comment]
Ledger need to add zclassic before the btcp fork!!!

**Comment by sandeepnailwal** [comment]
Desperately need zclassic support before the BTCP fork.

**Comment by xnet1** [comment]
Yes, please add ledger support for ZCL Soon

**Comment by petlap** [comment]
Ledger add ZCL before the fork please, this is gonna be huge

**Comment by aurelius2001** [comment]
Please add ZCL before the fork please! Tons of friends and family are waiting on this support!Thanks!

**Comment by LordZive** [comment]
Hi Ledger, It would be great if you add support for BTCP fork :-)

**Comment by Jackychans** [comment]
well, may anyone let me know when it will be available on chrome app store ?

**Comment by interbiznw** [comment]
@KirkBallou  I think more is needed for the actual device side for ZCL, correct me if I am wrong, but the Bitcoin app for the ledger nano s will need integration also.

**Comment by ChocolateDon** [comment]
Ledger please!

**Pull request closed without merging**
