### PR TITLE
added support for verge

### PR DESCRIPTION
**Pull request by vergecurrency**

### CODE REVIEW

**Comment by StanFaas** [comment]
Will Verge get added to the offline wallet? If yes, do you have any ETA?

**Comment by Heldex** [comment]
add please

**Comment by Chinafreak** [comment]
Add this features, please!

**Comment by josescasanova** [comment]
Any update on this? Want me to fix the conflict?

**Comment by Chinafreak** [comment]
I guess they want money for that, even if the code is done:

https://trello.com/c/4Aa7Ug5a/20-altcoin-support-information

**Comment by MrAoku** [comment]
Add it please, it's booming

**Comment by vonpupp** [comment]
Please consider supporting it. Thx

**Comment by Willeym26** [comment]
add it please, it's the best addition to put on

**Comment by DanielvanCleef** [comment]
Ledger is asking € 99000,- for the the app to be developed. Is it possible the community can pay for it?
It might be possible if enough hodlers are willing.

**Comment by GCHPX** [comment]
It would be awesome if you would add XVG to ledger!

**Comment by mystycs** [comment]
Agreed, add to nano s!

**Comment by aalgabre** [comment]
any update on this?

**Comment by db0mbase** [comment]
Please add Verge #AVG to the Ledger Nano S- Thanks! 👍

**Comment by ajaynarang** [comment]
Could you please XVG to nano s. MUCH NEEDED.

**Comment by IfaqYurmama** [comment]
The only thing this shitcoin is good for is a constant and never-ending stream of drama

**Pull request closed without merging**
